#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

echo "* Setup ruby env"
echo "gem: --no-document" >> /opt/local/etc/gemrc
gem install bundler
gem install geminabox
gem install thin
# fix thin
sed -i "s#/usr/bin/env ruby#/opt/local/bin/ruby#" /opt/local/bin/thin
# fix rubygems nfs lock issue
sed -i "s#rescue Errno::ENOLCK#rescue Errno::EINVAL#g" /opt/local/lib/ruby/2.7.0/rubygems.rb

groupadd -g 1100 ruby
useradd -m -s /usr/bin/bash -d /home/ruby -u 1100 -g ruby ruby
passwd -N ruby
passwd -d ruby

rm -rf /var/zoneinit/tmp
mkdir -p /home/ruby/www/gemserver
mv /opt/local/tmp/config.ru /home/ruby/www/gemserver/config.ru
chown -R ruby:ruby /home/ruby/www

# Configuring image specific packages
echo "* Configuring image specific packages.";
svccfg import /opt/local/lib/svc/manifest/gemsrv.xml

# Clean up
echo "* Cleaning up."
pkgin -y remove gmake
pkgin -y remove gcc7

rm /root/customize
rm -rf /opt/local/tmp

# Prepare image for provisioning
sm-prepare-image -y
